"""
api/app/db/models/nl_query.py
─────────────────────────────
SQLAlchemy ORM models for M3 — NL-to-SQL.

Two tables:
  M3TableEmbedding  — pgvector embeddings of table descriptions (one per table).
  NLQueryHistory    — append-only audit log of every processed NL query.

Note: vector columns use raw text representation ("[0.1,0.2,...]") because
we execute all pgvector operations via text() SQL to avoid requiring the
pgvector SQLAlchemy extension at ORM definition time.  The column is mapped
as Text here; actual vector math happens in context_builder.py via text().
"""

import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    Index,
    Integer,
    String,
    Text,
    TIMESTAMP,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import ARRAY, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class M3TableEmbedding(Base):
    """
    One row per indexed table for a datasource + schema.

    The `embedding` column stores the pgvector as a Python string
    ("[0.1,0.2,...]").  We never read it back through the ORM — all
    similarity queries go through raw SQL (text()) to use the <=> operator.
    """

    __tablename__ = "m3_table_embeddings"

    __table_args__ = (
        UniqueConstraint(
            "datasource_id", "tenant_id", "schema_name", "table_name",
            name="uq_m3_table_embeddings",
        ),
        Index("idx_m3_emb_datasource", "datasource_id", "tenant_id", "schema_name"),
        # NOTE: the HNSW index is created in the migration (DDL-only, not in ORM).
    )

    id:             Mapped[uuid.UUID]     = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    datasource_id:  Mapped[uuid.UUID]     = mapped_column(UUID(as_uuid=True), nullable=False)
    tenant_id:      Mapped[str]           = mapped_column(String(100), nullable=False)
    schema_name:    Mapped[str]           = mapped_column(String(255), nullable=False)
    table_name:     Mapped[str]           = mapped_column(String(255), nullable=False)
    embedded_text:  Mapped[str]           = mapped_column(Text, nullable=False)       # the text that was embedded
    # Stored as text but holds a pgvector literal e.g. "[0.1,0.2,...]"
    # We never read this column back through SQLAlchemy — only via raw SQL.
    embedding:      Mapped[str]           = mapped_column(Text, nullable=False)
    indexed_at:     Mapped[datetime]      = mapped_column(TIMESTAMP, nullable=False, server_default=func.now())


class NLQueryHistory(Base):
    """
    Append-only audit log of every NL query processed by M3.

    Each row records:
      - The original question from the user
      - The SQL generated by the LLM
      - The SQL that was actually executed (may differ after user edit)
      - Which tables were selected by the context builder
      - Execution outcome (row_count, exec_ms, error)
      - Optional human feedback (is_correct)

    This table is the source for few-shot training examples — rows where
    is_correct=True are candidates for the few-shot index.
    """

    __tablename__ = "nl_query_history"

    __table_args__ = (
        Index("idx_nlq_datasource", "datasource_id", "tenant_id", "created_at"),
        Index("idx_nlq_user",       "user_id",       "tenant_id", "created_at"),
    )

    id:             Mapped[uuid.UUID]     = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    datasource_id:  Mapped[uuid.UUID]     = mapped_column(UUID(as_uuid=True), nullable=False)
    tenant_id:      Mapped[str]           = mapped_column(String(100), nullable=False)
    user_id:        Mapped[str]           = mapped_column(String(100), nullable=False)
    schema_name:    Mapped[str]           = mapped_column(String(255), nullable=False)

    # What the user asked.
    question:       Mapped[str]           = mapped_column(Text, nullable=False)

    # SQL as produced by the LLM (before any user modification).
    generated_sql:  Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # SQL that was actually executed (the user may have edited generated_sql).
    executed_sql:   Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Tables that the context builder chose to include in the prompt.
    tables_selected: Mapped[Optional[list]] = mapped_column(ARRAY(Text), nullable=True, default=list)

    # Which Ollama model was called for SQL generation.
    model_used:     Mapped[Optional[str]] = mapped_column(String(100), nullable=True)

    # Execution metrics (null if execution never reached due to earlier error).
    row_count:      Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    exec_ms:        Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    # Human feedback: True = confirmed correct, False = flagged as wrong, None = not rated.
    is_correct:     Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)

    # Null on success.  Populated when the pipeline or execution raises an error.
    error_message:  Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    created_at:     Mapped[datetime]      = mapped_column(TIMESTAMP, nullable=False, server_default=func.now())
