-- =============================================================================
-- 003_create_nl_query.sql  —  M3: NL-to-SQL tables
-- =============================================================================
-- Run order: after 001_create_datasources.sql and 002_create_annotations.sql
--
-- Creates:
--   m3_table_embeddings  — pgvector embeddings of table+column descriptions
--                          used for semantic table selection at query time
--   nl_query_history     — immutable record of every NL query executed
--
-- Prerequisites:
--   PostgreSQL 14+  with  pgvector  AND  Apache AGE  extensions installed.
--   pgvector install:  https://github.com/pgvector/pgvector
--   Apache AGE install: https://age.apache.org/
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 0.  Extensions
-- ---------------------------------------------------------------------------

-- pgvector: stores and searches high-dimensional float vectors.
-- nomic-embed-text (768-dim) and mxbai-embed-large (1024-dim) both fit here;
-- we default to 768 but the column is created with 768 dims.
-- NOTE: requires superuser or pg_extension privilege.
CREATE EXTENSION IF NOT EXISTS vector;

-- Apache AGE: property-graph layer for schema join-path traversal.
-- Falls back gracefully if unavailable (context_builder catches the error).
CREATE EXTENSION IF NOT EXISTS age;


-- ---------------------------------------------------------------------------
-- 1.  pgvector embedding store for table descriptions
-- ---------------------------------------------------------------------------
--
-- One row per table that has at least one annotation (table description OR
-- at least one column annotation).  Built offline by the /index endpoint
-- and kept in sync when M2 annotations change.
--
-- Dimensionality: 768 matches nomic-embed-text output.
-- If you switch to mxbai-embed-large (1024) you must DROP and recreate
-- this table (or use a USING expression to cast).
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS m3_table_embeddings (
    id              UUID         NOT NULL DEFAULT gen_random_uuid(),
    datasource_id   UUID         NOT NULL,
    tenant_id       VARCHAR(100) NOT NULL,
    schema_name     VARCHAR(255) NOT NULL,
    table_name      VARCHAR(255) NOT NULL,
    -- The exact text that was fed to the embedding model — stored for
    -- debugging and to detect stale embeddings.
    embedded_text   TEXT         NOT NULL,
    -- The 768-dimensional vector produced by nomic-embed-text.
    embedding       vector(768)  NOT NULL,
    indexed_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_m3_table_embeddings PRIMARY KEY (id),
    -- Only one embedding per table per datasource per tenant.
    CONSTRAINT uq_m3_table_embeddings
        UNIQUE (datasource_id, tenant_id, schema_name, table_name)
);

-- Fast lookup when re-indexing a datasource.
CREATE INDEX IF NOT EXISTS idx_m3_emb_datasource
    ON m3_table_embeddings (datasource_id, tenant_id, schema_name);

-- HNSW index for fast approximate nearest-neighbour search using cosine distance.
-- HNSW (hierarchical navigable small world) is preferred over IVFFlat for
-- our use case because it:
--   - requires no minimum row count to build
--   - offers better recall at the same query latency
--   - supports incremental inserts without rebuild
-- ef_construction=128 and m=16 are good defaults for tables of <100k rows.
CREATE INDEX IF NOT EXISTS idx_m3_emb_hnsw
    ON m3_table_embeddings
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 128);


-- ---------------------------------------------------------------------------
-- 2.  NL query history
-- ---------------------------------------------------------------------------
--
-- Append-only audit trail of every NL query processed by M3.
-- Useful for:
--   - Debugging (see what SQL was generated for a question)
--   - Building few-shot examples (queries with is_correct=true)
--   - Audit trail for financial systems
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS nl_query_history (
    id              UUID         NOT NULL DEFAULT gen_random_uuid(),
    datasource_id   UUID         NOT NULL,
    tenant_id       VARCHAR(100) NOT NULL,
    user_id         VARCHAR(100) NOT NULL,
    schema_name     VARCHAR(255) NOT NULL,

    -- The raw question as the user typed it.
    question        TEXT         NOT NULL,

    -- The SQL generated by the LLM (before any user edit).
    generated_sql   TEXT,

    -- The SQL that was actually executed (may differ if the user edited it).
    executed_sql    TEXT,

    -- Which tables the context builder selected for the prompt.
    tables_selected TEXT[]       DEFAULT '{}',

    -- Which Ollama model produced the SQL.
    model_used      VARCHAR(100),

    -- Execution results.
    row_count       INTEGER,
    exec_ms         INTEGER,

    -- Human feedback — NULL = not yet rated.
    is_correct      BOOLEAN,

    -- NULL on success; populated on pipeline or execution error.
    error_message   TEXT,

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_nl_query_history PRIMARY KEY (id)
);

-- Lookup by datasource (list recent queries for a source).
CREATE INDEX IF NOT EXISTS idx_nlq_datasource
    ON nl_query_history (datasource_id, tenant_id, created_at DESC);

-- Lookup by user (personal query history).
CREATE INDEX IF NOT EXISTS idx_nlq_user
    ON nl_query_history (user_id, tenant_id, created_at DESC);


-- ---------------------------------------------------------------------------
-- 3.  updated_at trigger helper (reuses the function from 001)
-- ---------------------------------------------------------------------------
-- The nl_query_history table is intentionally append-only — no updated_at.
-- m3_table_embeddings is updated in-place (upsert) so it does not need one
-- either (indexed_at is reset on each upsert).


-- ---------------------------------------------------------------------------
-- 4.  Apache AGE — create the schema-graph (idempotent)
-- ---------------------------------------------------------------------------
--
-- The graph stores Table nodes and JOINS_ON edges built from
-- table_relationships.  Built/refreshed by the /index endpoint.
--
-- If AGE is not installed the DO block catches the error and logs it so
-- the rest of the migration still succeeds.
-- ---------------------------------------------------------------------------

DO $$
BEGIN
    EXECUTE 'LOAD ''age''';
    EXECUTE 'SET search_path = ag_catalog, "$user", public';

    IF NOT EXISTS (
        SELECT 1
        FROM ag_catalog.ag_graph
        WHERE name = 'insightx_schema_graph'
    ) THEN
        PERFORM ag_catalog.create_graph('insightx_schema_graph');
        RAISE NOTICE 'Created graph insightx_schema_graph';
    ELSE
        RAISE NOTICE 'Graph already exists.';
    END IF;

EXCEPTION
WHEN OTHERS THEN
    RAISE NOTICE 'AGE unavailable: %', SQLERRM;
END;
$$;
